goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../clojure/browser/event.js", ['clojure.browser.event'], ['cljs.core', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.events']);
goog.addDependency("../clojure/browser/net.js", ['clojure.browser.net'], ['goog.net.xpc.CfgFields', 'goog.net.XhrIo', 'goog.json', 'goog.Uri', 'cljs.core', 'goog.net.EventType', 'goog.net.xpc.CrossPageChannel', 'clojure.browser.event']);
goog.addDependency("../weasel/impls/websocket.js", ['weasel.impls.websocket'], ['cljs.core', 'clojure.browser.net', 'goog.net.WebSocket', 'clojure.browser.event']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../weasel/repl.js", ['weasel.repl'], ['weasel.impls.websocket', 'cljs.core', 'clojure.browser.net', 'cljs.reader', 'clojure.browser.event']);
goog.addDependency("../cljs/core/async/impl/protocols.js", ['cljs.core.async.impl.protocols'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/buffers.js", ['cljs.core.async.impl.buffers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/dispatch.js", ['cljs.core.async.impl.dispatch'], ['cljs.core', 'cljs.core.async.impl.buffers']);
goog.addDependency("../cljs/core/async/impl/channels.js", ['cljs.core.async.impl.channels'], ['cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/ioc_helpers.js", ['cljs.core.async.impl.ioc_helpers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/timers.js", ['cljs.core.async.impl.timers'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async.js", ['cljs.core.async'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols', 'cljs.core.async.impl.ioc_helpers', 'cljs.core.async.impl.timers']);
goog.addDependency("../om/dom.js", ['om.dom'], ['cljs.core']);
goog.addDependency("../om/core.js", ['om.core'], ['goog.dom', 'cljs.core', 'om.dom', 'goog.ui.IdGenerator']);
goog.addDependency("../sudoku/game.js", ['sudoku.game'], ['cljs.core']);
goog.addDependency("../sudoku/core.js", ['sudoku.core'], ['cljs.core', 'om.dom', 'om.core', 'sudoku.game']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../figwheel/client.js", ['figwheel.client'], ['goog.net.jsloader', 'cljs.core', 'cljs.core.async', 'clojure.string', 'cljs.reader']);
goog.addDependency("../sudoku/dev.js", ['sudoku.dev'], ['weasel.repl', 'cljs.core', 'cljs.core.async', 'sudoku.core', 'figwheel.client']);
goog.addDependency("../sudoku/appstate.js", ['sudoku.appstate'], ['cljs.core', 'om.dom', 'om.core', 'sudoku.game']);
goog.addDependency("../sudoku/history.js", ['sudoku.history'], ['sudoku.appstate', 'cljs.core']);
goog.addDependency("../sudoku/components/board.js", ['sudoku.components.board'], ['sudoku.appstate', 'cljs.core', 'om.dom', 'om.core', 'sudoku.game']);
goog.addDependency("../sudoku/components/historymenu.js", ['sudoku.components.historymenu'], ['cljs.core']);
goog.addDependency("../clojure/walk.js", ['clojure.walk'], ['cljs.core']);
goog.addDependency("../sudoku/components/palette.js", ['sudoku.components.palette'], ['cljs.core', 'om.dom', 'om.core']);
goog.addDependency("../ankha/core.js", ['ankha.core'], ['goog.crypt', 'cljs.core', 'om.dom', 'goog.object', 'om.core', 'clojure.string', 'goog.crypt.Md5', 'cljs.reader', 'clojure.walk']);
goog.addDependency("../sudoku/components/mainmenu.js", ['sudoku.components.mainmenu'], ['cljs.core']);
goog.addDependency("../sudoku/components/newboardmenu.js", ['sudoku.components.newboardmenu'], ['cljs.core']);